import type { HistoricalCampaign } from "./intelligence-domain";

const c = (campaign: HistoricalCampaign) => campaign;

export const INTELLIGENCE_FIXTURE_VERSION = "northstar-demo-v1.0";

export const demoCampaigns: HistoricalCampaign[] = [
  c({ campaignId: "camp_8842", name: "DC Summer Bundle", region: "MD-DC", product: "pizza", objective: "sales", jtd: "promote_lto", jtdConfidence: .94, spend: 945, impressions: 92000, reach: 43000, clicks: 2100, landingPageViews: 1680, conversions: 210, revenue: 4347, daysActive: 21, dailySpend: 45, trackingQuality: "good", ageDays: 8, creativePattern: "urgency + value bundle", audiencePattern: "broad local prospecting", offerPattern: "time-bound meal bundle" }),
  c({ campaignId: "camp_9107", name: "Richmond Game Night Feast", region: "VA-Richmond", product: "pizza", objective: "sales", jtd: "promote_lto", jtdConfidence: .91, spend: 1050, impressions: 101000, reach: 50000, clicks: 2525, landingPageViews: 1980, conversions: 245, revenue: 5355, daysActive: 21, dailySpend: 50, trackingQuality: "good", ageDays: 12, creativePattern: "occasion + value bundle", audiencePattern: "broad local prospecting", offerPattern: "event-led bundle" }),
  c({ campaignId: "camp_7731", name: "Philly Weekend Special", region: "PA-Philadelphia", product: "pizza", objective: "sales", jtd: "promote_lto", jtdConfidence: .89, spend: 880, impressions: 87000, reach: 41000, clicks: 1740, landingPageViews: 1320, conversions: 145, revenue: 2755, daysActive: 18, dailySpend: 49, trackingQuality: "good", ageDays: 28, creativePattern: "price-first urgency", audiencePattern: "interest-led local", offerPattern: "weekend discount" }),
  c({ campaignId: "camp_6614", name: "DC Family Meal Test", region: "MD-DC", product: "pizza", objective: "sales", jtd: "promote_lto", jtdConfidence: .87, spend: 760, impressions: 76000, reach: 35000, clicks: 1368, landingPageViews: 1020, conversions: 92, revenue: 1656, daysActive: 16, dailySpend: 48, trackingQuality: "good", ageDays: 17, creativePattern: "family convenience", audiencePattern: "parent interests", offerPattern: "family bundle" }),
  c({ campaignId: "camp_5509", name: "Richmond Late Night Deal", region: "VA-Richmond", product: "pizza", objective: "sales", jtd: "promote_lto", jtdConfidence: .84, spend: 690, impressions: 73000, reach: 32000, clicks: 1022, landingPageViews: 780, conversions: 58, revenue: 870, daysActive: 15, dailySpend: 46, trackingQuality: "good", ageDays: 35, creativePattern: "late-night discount", audiencePattern: "daypart interest", offerPattern: "discount" }),
  c({ campaignId: "camp_4498", name: "DC Flash Offer Early Read", region: "MD-DC", product: "pizza", objective: "sales", jtd: "promote_lto", jtdConfidence: .82, spend: 42, impressions: 6400, reach: 4100, clicks: 190, landingPageViews: 155, conversions: 2, revenue: 336, daysActive: 2, dailySpend: 21, trackingQuality: "good", ageDays: 2, creativePattern: "flash urgency", audiencePattern: "broad local", offerPattern: "flash deal" }),

  c({ campaignId: "camp_3201", name: "DC New Customer Welcome", region: "MD-DC", product: "pizza", objective: "sales", jtd: "acquire_new", jtdConfidence: .93, spend: 1320, impressions: 125000, reach: 66000, clicks: 3000, landingPageViews: 2400, conversions: 225, revenue: 4950, daysActive: 30, dailySpend: 44, trackingQuality: "good", ageDays: 5, creativePattern: "first-order confidence", audiencePattern: "broad prospecting excluding buyers", offerPattern: "first-order incentive" }),
  c({ campaignId: "camp_3202", name: "Richmond First Slice", region: "VA-Richmond", product: "pizza", objective: "sales", jtd: "acquire_new", jtdConfidence: .90, spend: 1200, impressions: 118000, reach: 62000, clicks: 2478, landingPageViews: 1920, conversions: 172, revenue: 3440, daysActive: 28, dailySpend: 43, trackingQuality: "good", ageDays: 18, creativePattern: "product discovery", audiencePattern: "broad prospecting", offerPattern: "first-order incentive" }),
  c({ campaignId: "camp_3203", name: "Philly Try Us", region: "PA-Philadelphia", product: "pizza", objective: "sales", jtd: "acquire_new", jtdConfidence: .88, spend: 980, impressions: 98000, reach: 54000, clicks: 1764, landingPageViews: 1390, conversions: 105, revenue: 1890, daysActive: 24, dailySpend: 41, trackingQuality: "good", ageDays: 31, creativePattern: "social proof", audiencePattern: "food interest prospecting", offerPattern: "entry offer" }),
  c({ campaignId: "camp_3204", name: "DC Prospecting Broad V2", region: "MD-DC", product: "pizza", objective: "sales", jtd: "acquire_new", jtdConfidence: .86, spend: 1550, impressions: 142000, reach: 68000, clicks: 1988, landingPageViews: 1500, conversions: 75, revenue: 1275, daysActive: 30, dailySpend: 52, trackingQuality: "good", ageDays: 11, creativePattern: "generic product", audiencePattern: "broad prospecting", offerPattern: "none" }),
  c({ campaignId: "camp_3205", name: "Richmond Acquisition Tracking Migration", region: "VA-Richmond", product: "pizza", objective: "sales", jtd: "acquire_new", jtdConfidence: .81, spend: 820, impressions: 84000, reach: 42000, clicks: 1680, landingPageViews: 1320, conversions: 160, revenue: 420, daysActive: 20, dailySpend: 41, trackingQuality: "critical", ageDays: 14, creativePattern: "product discovery", audiencePattern: "broad prospecting", offerPattern: "entry offer" }),

  c({ campaignId: "camp_7401", name: "DC Office Catering", region: "MD-DC", product: "catering", objective: "leads", jtd: "drive_catering", jtdConfidence: .96, spend: 810, impressions: 48000, reach: 29000, clicks: 1440, landingPageViews: 1100, conversions: 96, revenue: 0, daysActive: 25, dailySpend: 32, trackingQuality: "good", ageDays: 9, creativePattern: "group convenience + proof", audiencePattern: "office decision makers", offerPattern: "catering consultation" }),
  c({ campaignId: "camp_7402", name: "Richmond Catering Leads", region: "VA-Richmond", product: "catering", objective: "leads", jtd: "drive_catering", jtdConfidence: .94, spend: 760, impressions: 44000, reach: 27000, clicks: 1144, landingPageViews: 900, conversions: 68, revenue: 0, daysActive: 22, dailySpend: 35, trackingQuality: "good", ageDays: 20, creativePattern: "event planning ease", audiencePattern: "event planners", offerPattern: "catering quote" }),
  c({ campaignId: "camp_7403", name: "Philly Catering Inquiry", region: "PA-Philadelphia", product: "catering", objective: "leads", jtd: "drive_catering", jtdConfidence: .92, spend: 700, impressions: 42000, reach: 26000, clicks: 840, landingPageViews: 650, conversions: 41, revenue: 0, daysActive: 20, dailySpend: 35, trackingQuality: "good", ageDays: 27, creativePattern: "menu variety", audiencePattern: "business interests", offerPattern: "catering quote" }),
  c({ campaignId: "camp_7404", name: "DC Catering Broad", region: "MD-DC", product: "catering", objective: "leads", jtd: "drive_catering", jtdConfidence: .87, spend: 920, impressions: 55000, reach: 31000, clicks: 770, landingPageViews: 560, conversions: 24, revenue: 0, daysActive: 24, dailySpend: 38, trackingQuality: "good", ageDays: 16, creativePattern: "generic catering", audiencePattern: "broad local", offerPattern: "contact us" }),
  c({ campaignId: "camp_7405", name: "Richmond Catering Test", region: "VA-Richmond", product: "catering", objective: "leads", jtd: "drive_catering", jtdConfidence: .72, spend: 75, impressions: 4200, reach: 3000, clicks: 105, landingPageViews: 80, conversions: 4, revenue: 0, daysActive: 3, dailySpend: 25, trackingQuality: "good", ageDays: 3, creativePattern: "event planning", audiencePattern: "event interests", offerPattern: "quote" }),

  c({ campaignId: "camp_8201", name: "DC Loyalty App", region: "MD-DC", product: "loyalty", objective: "traffic", jtd: "loyalty_signup", jtdConfidence: .95, spend: 520, impressions: 68000, reach: 41000, clicks: 2380, landingPageViews: 1880, conversions: 0, revenue: 0, daysActive: 18, dailySpend: 29, trackingQuality: "good", ageDays: 7, creativePattern: "member benefits", audiencePattern: "engaged customers", offerPattern: "loyalty perks" }),
  c({ campaignId: "camp_8202", name: "Philly Rewards", region: "PA-Philadelphia", product: "loyalty", objective: "traffic", jtd: "loyalty_signup", jtdConfidence: .91, spend: 490, impressions: 65000, reach: 39000, clicks: 1820, landingPageViews: 1365, conversions: 0, revenue: 0, daysActive: 17, dailySpend: 29, trackingQuality: "good", ageDays: 22, creativePattern: "earn rewards", audiencePattern: "recent customers", offerPattern: "points" }),
];
